# site settings
title: Casolanament
subtitle: by Lídia Embuena
email: lembuena@gmail.com
description:Hola! 
I am Lídia Embuena. I was born in Barcelona and for the last 9 years, I have lived in great cities like San Francisco, Edinburgh and London where I have grown as a person and professionally. I recently moved to New York city with my family, and I am discovering the opportunities that the city offers me and enjoying 
I have a bachelor's degree in Pedagogy and Education Science and I have extensive experience in teaching, course design, and education project coordination. Following my interest in the social aspects of technology, during the last years, I focused my career in the tech industry where I have worked in data analysis, quality assurance, UX, and localization for major tech companies. 
I am currently studying an MSc in Digital Education at the University of Edinburgh (fully online) with the main intention to develop and consolidate my skills in the e-learning arena./> and released under the Creative Commons.
baseurl: "/lidiaembuena.github.io" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
